### ISSUE TITLE
北航云盘更新了，目前的这个仓库好像暂时用不了，可以麻烦更新一下代码吗

### ISSUE THREAD

**Issue by eecoder-dyf** [xdedss/dist_bhpan#5]
更新以后可以正常安装并登陆，但以后输入`bhpan ls home` 会出现如下报错：
```
Traceback (most recent call last):
  File "/mnt/d/miniconda3/bin/bhpan", line 33, in <module>
    sys.exit(load_entry_point('bhpan==0.0.2', 'console_scripts', 'bhpan')())
  File "/mnt/d/miniconda3/lib/python3.10/site-packages/bhpan-0.0.2-py3.10.egg/pancli/pancli.py", line 650, in main
  File "/mnt/d/miniconda3/lib/python3.10/site-packages/bhpan-0.0.2-py3.10.egg/pancli/pancli.py", line 560, in <lambda>
  File "/mnt/d/miniconda3/lib/python3.10/site-packages/bhpan-0.0.2-py3.10.egg/pancli/pancli.py", line 228, in list_dir
  File "/mnt/d/miniconda3/lib/python3.10/site-packages/bhpan-0.0.2-py3.10.egg/pancli/utils/api_manager.py", line 137, in get_resource_info_by_path
  File "/mnt/d/miniconda3/lib/python3.10/site-packages/bhpan-0.0.2-py3.10.egg/pancli/utils/api.py", line 93, in post_json
pancli.utils.api.ApiException: api returned HTTP 404
{"errcode":404024,"errmsg":"路径不存在","causemsg":""}
```

**Comment by xdedss** [comment]
api变了，正在排查

**Comment by xdedss** [comment]
测试一下dev-v7fiix分支能否正常使用

**Comment by eecoder-dyf** [comment]
> 测试一下dev-v7fiix分支能否正常使用

无法正常使用upload功能，但可能和北航云盘api无关，处理本地文件有问题

```
(base) dyf@dyf-yuki:~$ bhpan upload /home/dyf/adduser.sh home/test/
1693107408.3916445
/home/dyf/adduser.sh: 127(127.0)
uploading...
Traceback (most recent call last):
  File "/mnt/d/miniconda3/lib/python3.10/site-packages/bhpan-0.0.2-py3.10.egg/pancli/utils/api_manager.py", line 141, in get_resource_info_by_path
  File "/mnt/d/miniconda3/lib/python3.10/site-packages/bhpan-0.0.2-py3.10.egg/pancli/utils/api.py", line 98, in post_json
pancli.utils.api.ApiException: api returned HTTP 404
{"cause":"文件或目录对象不存在 (adduser.sh)。（错误提供者：EVFS，错误值：16778514，错误位置：ncEVFSQueryHandler.cpp:2464）","code":404002006,"message":"请求的文件或目录不存在。"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/d/miniconda3/bin/bhpan", line 33, in <module>
    sys.exit(load_entry_point('bhpan==0.0.2', 'console_scripts', 'bhpan')())
  File "/mnt/d/miniconda3/lib/python3.10/site-packages/bhpan-0.0.2-py3.10.egg/pancli/pancli.py", line 684, in main
  File "/mnt/d/miniconda3/lib/python3.10/site-packages/bhpan-0.0.2-py3.10.egg/pancli/pancli.py", line 560, in <lambda>
  File "/mnt/d/miniconda3/lib/python3.10/site-packages/bhpan-0.0.2-py3.10.egg/pancli/pancli.py", line 78, in upload_file
  File "/mnt/d/miniconda3/lib/python3.10/site-packages/bhpan-0.0.2-py3.10.egg/pancli/utils/api_manager.py", line 284, in upload_file
  File "/mnt/d/miniconda3/lib/python3.10/site-packages/bhpan-0.0.2-py3.10.egg/pancli/utils/api_manager.py", line 132, in get_resource_id
  File "/mnt/d/miniconda3/lib/python3.10/site-packages/bhpan-0.0.2-py3.10.egg/pancli/utils/api_manager.py", line 145, in get_resource_info_by_path
KeyError: 'errcode'
```

**Comment by xdedss** [comment]
dev-v7fix已更新，上传应该可以用了
